language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
  - "web/node_modules"
script:
  - cd $TRAVIS_BUILD_DIR/api
  - yarn install
  - yarn build
  - cd $TRAVIS_BUILD_DIR/web
  - yarn install
  - yarn test