language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
  - web/node_modules
  - api/node_modules
install:
  - npm i -g codecov
script:
  - cd $TRAVIS_BUILD_DIR/api
  - yarn install
  - yarn test --collectCoverage
  - codecov
  - yarn build
  - cd $TRAVIS_BUILD_DIR/web
  - yarn install
  - yarn test --collectCoverage
  - codecov
  - yarn build
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: cloudfoundry
  api: https://api.run.pcfbeta.io
  organization: pivot-ddubson
  space: development
  manifest: .
  username:
    secure: ixrJoJ5DEbF/UGrzQAnwB1pnTbV2QU9kSQ+X/O0NEqW1WWDt2jqG0VIH08B3ff/oYzURh6Q5gjufkU5XpqSMTSJfNG2T1h7WvICy88MP8H1e1T99Vxrc/1LBBDMLlozomNpAwKuFeSqFXb3dlyl4bql810AEhvI2bSpE2sfAtVBKx1ilILW5d/79ofo2eP6Qu22Kez7mi+dlye4FxQGAJZeRTf3iJlzidSZ7fzgUUfK8Cq3piJkiAtmKQTyrS7QF4S+QtzqIWIrP2qDS0pNhNTeJMGJkY0/0ElmPhtEEjkeIFILIavxi6cd/JHO3msolIg+/EeYGCQ6nV29vL5mJAVl6hqR4Q61R3cXBXQ8w0jqQkrAtV2+oXw5W4K1UwIw7ga30RTrdoEQ7Dk/sQKbiJOwBVchEZb/mkdIxcL9d+gsNb70evS9HMQG4lLBb5XRrh7MebkQ1iEitLU1nGSC63r6XwfJGaLG7W1569Xr+O7/DXG+xofxRJkZdId8ckY5z+xS4SeJdnASCVknK7a2/HipYfY0hR1itINADcOHYZTkQJ5RNSCzBkER+XbGK5nXeDvxxvbtS5J6WnPIorItWPKAQmujPh6iWBYk3A3jqCWoAMKLRjJezGw6MJCW3/0giCTZK46NMSeSSrPHz7pncfgPtQ1poWZoUukLUv/mbEbY=
  password:
    secure: bF1H4zuBMJlWAS/GdMbhFokwwGztNSfSzmsOUqFIouC+eMbai+LzCTiQlfWiHKJqAkmYLkv3oTqeBYxmuh3uj7yzMmyQ9i/N0MQ3R/OlHZxW6hnaEggvJlAvXtppPznvYK0RR15uGw5wUs8T7u+/T/eB+7cKEwJD0+33xod+J148jGKOBv2p5YVhA2b+0G7nug4/0ZNevuY8gUs+mxlbypqpNkWUzMCz6CPvw2KB0O3OC6Ql9jYTEmeoFsidYZDi7UPYEveKMLctZBTJ0Wp1wg/xsv9nrFPVLVpEUGNX3wKrfr5B8n24Zw2lNrAW9KZLMWYiDNkbRPlIg91ObXq4mpm2rUUNryisC9ti7tSnPnVMtZXLyh3kxThXSFO5rhINTeRtGQpxEcdJJl2M+NbRcWLGtWk1CEd1SDdFOVox/IUHq+FO/RrFOP1nMuCnpmByxz3tRDwwJP/ltbf9hiWNqS+hRg+ARg3XXvItdCD+QhQMJrDkXQz5nbX04EmIMZgTXWJcBwCzlYfru1/KXR0Fd1A5sY6iGvLOXHZ5wq2ozwetmQHLaqnYJH4MipNgkTtPLsMSW9cURbmbIkNVGMwPJbBM+oDpoEcpTkwYIdn8XhnspeQkJ+3VUEafzPLmkEGXf60Bcm/N5UeZKBG5bbscXZeTpF90jQCZOc1pPDhxyMw=
